name: React Automated Frontend Deployment

on:
  push:
    branches:
      - main  # Jab bhi aap frontend main branch par push karenge, pipeline chal paregi

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Executing Remote SSH Commands to Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 11092
          script: |
            cd /www/wwwroot/gradewiseaiv2.techmiresolutions.com
            
            # 1. Fresh code pull karo GitHub se
            git fetch --all
            git reset --hard origin/main
            
            # 2. Dependencies install karo aur naya maal build karo
            npm install
            npm run build
            
            # 3. Purani live files ko delete karo taake naya nishan bane
            rm -rf assets index.html vite.svg
            
            # 4. Naye dist folder ka maal utha kar root par phenko
            if [ -d "dist" ]; then
              cp -r dist/* .
              echo "✅ New Production Build deployed successfully to Root!"
            fi
            
            echo "🚀 Deployment Finished!"